// packages/react/src/JsonForms.tsx
/*
  The MIT License
  
  Copyright (c) 2018 EclipseSource Munich
  https://github.com/eclipsesource/jsonforms
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/
import * as React from 'react';
import * as _ from 'lodash';
import { connect } from 'react-redux';
import { UnknownRenderer } from './UnknownRenderer';
import {
  createId,
  JsonFormsProps,
  mapStateToDispatchRendererProps,
  removeId
} from '@jsonforms/core';

class JsonFormsDispatchRenderer extends React.Component<JsonFormsProps, { id: string }> {

  constructor(props) {
    super(props);
    if (this.isManageOwnID(props)) {
      this.state = {
        id: createId(props.uischema.scope)
      };
    } else {
      this.state = {
        id: undefined
      };
    }
  }

  isManageOwnID(props) {
    return props.uischema.type === 'Control';
  }

  componentWillUnmount() {
    if (this.isManageOwnID(this.props)) {
      removeId(this.state.id);
    }
  }

  render() {
    const { uischema, schema, path, renderers } = this.props as JsonFormsProps;
    const renderer = _.maxBy(renderers, r => r.tester(uischema, schema));
    if (renderer === undefined || renderer.tester(uischema, schema) === -1) {
      return <UnknownRenderer type={'renderer'} />;
    } else {
      const Render = renderer.renderer;
      return (
        <Render
          uischema={uischema}
          schema={schema}
          path={path}
          renderers={renderers}
          id={this.state.id}
        />
      );
    }
  }
}

export const JsonForms = connect(
  mapStateToDispatchRendererProps,
  null
)(JsonFormsDispatchRenderer);

// packages/angular/src/jsonforms.component.ts
/*
  The MIT License
  
  Copyright (c) 2018 EclipseSource Munich
  https://github.com/eclipsesource/jsonforms
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/
import * as _ from 'lodash';
import {
  ComponentFactoryResolver,
  Directive,
  Input,
  OnInit,
  Type,
  ViewContainerRef
} from '@angular/core';
import {
  JsonFormsProps,
  mapStateToDispatchRendererProps,
  UISchemaElement
} from '@jsonforms/core';
import { NgRedux } from '@angular-redux/store';
import 'rxjs/add/operator/map';
import { UnknownRenderer } from './unknown.component';
import { JsonFormsBaseRenderer } from './base.renderer';

@Directive({
  selector: 'jsonforms-outlet',
})
export class JsonFormsOutlet implements OnInit {

  @Input() uischema: UISchemaElement;

  constructor(
    private viewContainerRef: ViewContainerRef,
    private componentFactoryResolver: ComponentFactoryResolver,
    private ngRedux: NgRedux<any> ) {
  }

  ngOnInit(): void {
    const state$ = this.ngRedux.select().map(state =>
       mapStateToDispatchRendererProps(state, {uischema: this.uischema})
    );
    state$.subscribe(props => {
      const {renderers, schema, uischema} = props as JsonFormsProps;
      const renderer = _.maxBy(renderers, r => r.tester(uischema, schema));
      let bestComponent: Type<any> = UnknownRenderer;
      if (renderer !== undefined && renderer.tester(uischema, schema) !== -1) {
        bestComponent = renderer.renderer;
      }
      const componentFactory = this.componentFactoryResolver.resolveComponentFactory(bestComponent);
      this.viewContainerRef.clear();

      const componentRef = this.viewContainerRef.createComponent(componentFactory);
      if (componentRef.instance instanceof JsonFormsBaseRenderer) {
        const instance = (componentRef.instance as JsonFormsBaseRenderer);
        instance.uischema = uischema;
        instance.schema = schema;
      }
    });
  }

}
