// packages/angular/src/library/array-control.ts
/*
  The MIT License

  Copyright (c) 2017-2019 EclipseSource Munich
  https://github.com/eclipsesource/jsonforms

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/
import {
  JsonFormsState,
  mapStateToArrayControlProps,
  StatePropsOfArrayControl,
} from '@jsonforms/core';
import type { OnDestroy, OnInit } from '@angular/core';
import { JsonFormsAbstractControl } from './abstract-control';

export class JsonFormsArrayControl
  extends JsonFormsAbstractControl<StatePropsOfArrayControl>
  implements OnInit, OnDestroy
{
  protected mapToProps(state: JsonFormsState): StatePropsOfArrayControl {
    const props = mapStateToArrayControlProps(state, this.getOwnProps());
    return { ...props };
  }
}

// packages/vanilla/src/complex/array/ArrayControl.tsx
/*
  The MIT License

  Copyright (c) 2017-2019 EclipseSource Munich
  https://github.com/eclipsesource/jsonforms

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/
import range from 'lodash/range';
import React from 'react';
import { ArrayControlProps, composePaths } from '@jsonforms/core';
import { ResolvedJsonForms } from '@jsonforms/react';
import { VanillaRendererProps } from '../../index';

export const ArrayControl = ({
  classNames,
  data,
  label,
  path,
  schema,
  addItem,
  uischema,
  findUISchema,
  createDefaultValue
}: ArrayControlProps & VanillaRendererProps) => {
  return (
    <div className={classNames.wrapper}>
      <fieldset className={classNames.fieldSet}>
        <legend>
          <button
            className={classNames.button}
            onClick={() => addItem(path, createDefaultValue())}
          >
            +
          </button>
          <label className={'array.label'}>{label}</label>
        </legend>
        <div className={classNames.children}>
          {data ? (
            range(0, data.length).map(index => {
              const foundUISchema = findUISchema(schema, uischema.scope, path);
              const childPath = composePaths(path, `${index}`);

              return (
                <ResolvedJsonForms
                  schema={schema}
                  uischema={foundUISchema || uischema}
                  path={childPath}
                  key={childPath}
                />
              );
            })
          ) : (
            <p>No data</p>
          )}
        </div>
      </fieldset>
    </div>
  );
};
